# Generated by Django 4.2.7 on 2026-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='O mnie', max_length=200)),
                ('content', models.TextField(help_text='Opis kim jestem i moje doświadczenie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'O mnie',
                'verbose_name_plural': 'O mnie',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Tresc wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytana')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa technologii (np. Python, Django)', max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Logo lub ikona technologii', null=True, upload_to='technologies/')),
                ('description', models.TextField(help_text='Krótki opis technologii')),
                ('order', models.IntegerField(default=0, help_text='Kolejność wyświetlania')),
            ],
            options={
                'verbose_name': 'Technologia',
                'verbose_name_plural': 'Technologie',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł projektu', max_length=200)),
                ('description', models.TextField(help_text='Opis projektu')),
                ('image', models.ImageField(blank=True, help_text='Zrzut ekranu projektu', null=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True, help_text='Link do repozytorium GitHub')),
                ('live_link', models.URLField(blank=True, help_text='Link do działającej wersji')),
                ('order', models.IntegerField(default=0, help_text='Kolejność wyświetlnia')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('technologies', models.ManyToManyField(blank=True, help_text='Technologie uzyte w projekcie', to='portfolio.technology')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
